#
server:
  servlet:
    context-path: /
    session:
      timeout: 3600 # in seconds, so 60 min  # If a duration suffix is not specified, seconds will be used.
  compression:
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    enabled: true
  port: 8080

info:
  app:
    name: rag-api
    version: '@project.version@'

logging:
  level:
    com.epam.training.gen.ai: debug
    org.springframework: info
    org:
      hibernate: info
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
      enabled: true
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: false
        schema-name: public
        table-name: vector_store
        max-document-batch-size: 10000
    openai:
      api-key: ${API_KEY}
      base-url: https://ai-proxy.lab.epam.com
      chat:
        completions-path: /openai/deployments/gpt-4.1-mini-2025-04-14/chat/completions
        model: "gpt-4.1-mini-2025-04-14" #"gpt-4-turbo"
        base-url: ${OPEN_AI_ENDPOINT:https://ai-proxy.lab.epam.com}
        embeddings-path: /openai/deployments/text-embedding-ada-002/embeddings
  datasource:
    url: "jdbc:postgresql://localhost:5432/embeddings_db" #?stringtype=unspecified # 5433
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: none
    hibernate:
      ddl-auto: none
    show-sql: true

