
services:
  postgres:
    image: ankane/pgvector
    container_name: rag_pgvector
    environment:
      POSTGRES_DB: embeddings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgvector-db:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
